// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVa4dmM5x6CyVTyJBLrr7a8kYzLLbOAA8',
    appId: '1:785817696740:web:7c27fec10b3083dc79eff1',
    messagingSenderId: '785817696740',
    projectId: 'emart-37d0a',
    authDomain: 'emart-37d0a.firebaseapp.com',
    storageBucket: 'emart-37d0a.appspot.com',
    measurementId: 'G-K05JFZGRPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkUppsWXgFdYbtiEq5DUrQ3T3mSlHlqwA',
    appId: '1:785817696740:android:67dbd4d9d059104879eff1',
    messagingSenderId: '785817696740',
    projectId: 'emart-37d0a',
    storageBucket: 'emart-37d0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGcZ7-jTS6QUJDh5oUga61VHx_Aa4bIYU',
    appId: '1:785817696740:ios:87b2d5b1b39a69b079eff1',
    messagingSenderId: '785817696740',
    projectId: 'emart-37d0a',
    storageBucket: 'emart-37d0a.appspot.com',
    iosBundleId: 'com.example.emart',
  );
}
